name: Security Scan

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO- https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb stable main | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      # 🔎 Scan Python dependencies & configs
      - name: Trivy FS scan
        run: trivy fs --exit-code 1 --severity CRITICAL,HIGH .

      # 🔎 If you have a Dockerfile for deployment
      - name: Build and scan Docker image
        run: |
          docker build -t  vrajzigu/projects:latest .
          trivy image --exit-code 1 --severity CRITICAL,HIGH python-app:latest
