name: Docker Image Build and Push to DockerHub

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: docker build -t vrajzigu/ytchatbot:latest .
      - name: push image to docker hub
        run: |
          docker login -u vrajzigu -p ${{secrets.DOCKER_HUB_TOKEN}}
          docker push vrajzigu/ytchatbot:latest
